### ISSUE TITLE
Parsing javascript gives unexpected result

### ISSUE THREAD

**Issue by wendigo** [tdewolff/push#3]
I'm trying to integrate push with Caddy.

When testing it on my site I get some strange results: for https://serafin.tech/analytics.js push recognizes resources list: ```[/'+a+']```

**Comment by tdewolff** [comment]
I'm guessing the JS file is parsed as if it's an HTML/CSS/SVG file but it is not. Which mimetype do you pass for this JS file? It should not be parsed at all.

**Comment by tdewolff** [comment]
Can you clarify? Otherwise please close the issue.
