### ISSUE TITLE
Cycle detection

### ISSUE THREAD

**Issue by wendigo** [tdewolff/push#4]
I've observed that push is not able to cope with cyclic references when trying to List resources for given file. It falls into some kind of loop.

**Comment by tdewolff** [comment]
Hm, I need to think about wise solution for this one. I suppose the easiest way would be to implement `FileOpener` and keep a list of requested file paths and returns an error when a file is re-requested. What do you think?

**Comment by wendigo** [comment]
It should be sufficient I guess (or maybe just hash file locations and keep in a map uint64->struct{})

**Comment by mholt** [comment]
If they're file _locations_ I don't think you'd need a hash at all.

**Comment by tdewolff** [comment]
You can implement this yourself using the `FileOpener` interface, can this issue be closed then?
